using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;
namespace api
{
    // Generated by https://quicktype.io

namespace getFilmeResult
{
  using System;
  using System.Collections.Generic;

  using System.Globalization;
  using Newtonsoft.Json;
  using Newtonsoft.Json.Converters;

  public partial class TopLevel
  {
    [JsonProperty("id")]
    public string Id { get; set; }

    [JsonProperty("titulo")]
    public string Titulo { get; set; }

    [JsonProperty("ano")]
    public long Ano { get; set; }

    [JsonProperty("nota")]
    public double Nota { get; set; }
  }

  public partial class TopLevel
  {
    public static TopLevel[] FromJson(string json) => JsonConvert.DeserializeObject<TopLevel[]>(json, getFilmeResult.Converter.Settings);
  }

  public static class Serialize
  {
    public static string ToJson(this TopLevel[] self) => JsonConvert.SerializeObject(self, getFilmeResult.Converter.Settings);
  }

  internal static class Converter
  {
    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    {
      MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
      DateParseHandling = DateParseHandling.None,
      Converters = {
        new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
      },
    };
  }
}
}
